### ISSUE TITLE
Describe setup cost for netlifycms

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/rx-angular#209]
The goal is to see how much effort it would be to set it up and main it.

Link: https://www.netlifycms.org/

First research gave the setup of the CMD itself is pretty easy.

Following the steps in the description, I created 2 files in `path-to-docs/admin`:

index.html
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
</head>
<body>
<!-- Include the script that builds the page and powers Netlify CMS -->
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```

and config.yml
```yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
- name: "page"
  label: "Page"
  folder: "api"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
  - {label: Content, name: body, widget: "markdown"}
```

The first problem was I want it to be self-hosted. This includes to set up our own auth provider:

Resources I found:
- https://github.com/tylergaw/netlify-cms-github-oauth-provider-client-example
- https://glitch.com/edit/#!/netlify-cms-github-oauth-provider-example?path=README.md%3A1%3A0

UPDATE:

I found a better solution running `npx netlify-cms-proxy-server`

And changed the setting of `path-to-docs/admin/config.json` to:

```yml
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
```
:)

UPDATE:

Setup workspace target and experimented with collections, content and folder structures.

Checkout https://github.com/BioPhoton/rx-angular/tree/netlify-cms-research and run `yarn nx serve-docs-admin state` to test it.

IMHO for editing the MD files its good enough.

The only problem I see is the slug in the file
https://github.com/BioPhoton/rx-angular/blob/netlify-cms-research/libs/state/docs/api/rx-state.md

UPDATE:

fixed slug problem with better configs and a hack over path settings

config.yml
```yml
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master # Branch to update (optional; defaults to master)
media_folder: "docs/docs/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
- name: "partial"
  label: "Partial"
  summary: "{{filename}}.{{extension}}"
  folder: "docs/docs/partials/"
  path: "/"
  create: true
  fields:
    - {label: "Content", name: "body", widget: "markdown"}
- name: "state-page"
  label: "State Page"
  summary: "{{filename}}.{{extension}}"
  folder: "docs/docs/state/"
  path: "/"
  create: true
  fields:
    - {label: "Content", name: "body", widget: "markdown"}
- name: "template-page"
  label: "Template Page"
  summary: "{{filename}}.{{extension}}"
  folder: "docs/docs/template/"
  path: "/"
  create: true
  fields:
    - {label: "Content", name: "body", widget: "markdown"}
```

angular.json
```json
...
"docs": {
      "projectType": "application",
      "root": "docs",
      "sourceRoot": "docs/docs",
      "prefix": "rx-angular",
      "architect": {
        "serve-admin": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "parallel": true,
            "commands": [
              {
                "command": "npx serve docs/docs/admin"
              },
              {
                "command": "npx netlify-cms-proxy-server"
              }
            ]
          }
        },
        "serve": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "parallel": true,
            "commands": [
              {
                "command": "npx docsify-cli serve docs/docs"
              }
            ]
          }
        }
      }
    },
...
```

This is implemented in https://github.com/BioPhoton/rx-angular/blob/docs-generation-test
